/*
  FILE GENERATED BY write_build_no.bat
               *** DO NOT EDIT ***
  TO CHANGE ANY INFORMATION IN HERE PLEASE
  EDIT write_build_no.bat
  FORMAL BUILD NUMBER:25
*/
#define PRODUCT_VER_STRING "1.0.0.25"
#define FILE_VER_STRING "WIN-1.0.0.25"
#define FILE_VER_NUMBER 1, 0, 0, 25
