/*
  FILE GENERATED BY write_build_no.bat
               *** DO NOT EDIT ***
  TO CHANGE ANY INFORMATION IN HERE PLEASE
  EDIT write_build_no.bat
  FORMAL BUILD NUMBER:38
*/
#define PRODUCT_VER_STRING "1.3.2.38"
#define FILE_VER_STRING "WIN-1.3.2.38"
#define FILE_VER_NUMBER 1, 3, 2, 38
